### ISSUE TITLE
[Bug Report] Apollo dont disable mods

### ISSUE THREAD

**Issue by Raffymimii** [LunarClient/Apollo#140]
### Checklist before creating an issue:

- [X] I'm using the [latest version](https://github.com/LunarClient/Apollo/releases) of Apollo.
- [X] I'm using the latest version of Lunar Client. (Relaunched in the last hour)
- [X] I'm running Apollo on **ONLY** the backend server OR the proxy. **(YOU CANNOT RUN IT ON BOTH)**
- [X] I do **NOT** have both Apollo and the LEGACY API installed on the same server. **(YOU CANNOT RUN BOTH AT THE SAME TIME)**
- [X] I've gathered all screenshots, logs and appropriate information related to creating a bug report.

### Issue Description

I have a problem with apollo, I put the following mods disabled, but players can still use them

### Reproduction steps

```bash
1. Setup the mods.yml
2. Restart your server
3. Make a player join in the server
4. The mod won't be disabled
```

### Code Snippet (If applicable, if not write N/A)

N/A

### Versions

1.17

### Platforms

Spigot / Bukkit

### Server Version

1.17

### Modules

Optifine

### Screenshots

```bash
![IMAGE](https://imgur.com/fB3aE3E)
```

### Contact Information

```bash
Discord - Raffymimi
```

**Comment by DrPanayioths** [comment]
Optifine Is Not A Mod You Can Disable Using Appolo

**Comment by Raffymimii** [comment]
I'm sure of what you asked. I don't use other apollo functions and wouldn't know how to test them. In any case, I get an error when a player tries to enter:

```
[17:48:03] [Server thread/INFO]: [Apollo-Bukkit] Enabling Apollo-Bukkit v1.1.1
[17:48:04] [Server thread/WARN]: java.lang.RuntimeException: Unable to wrap value of type 'Color'!
[17:48:04] [Server thread/WARN]: 	at apollo-bukkit-1.1.1.jar//com.lunarclient.apollo.option.OptionsImpl.wrapValue(OptionsImpl.java:277)
[17:48:04] [Server thread/WARN]: 	at apollo-bukkit-1.1.1.jar//com.lunarclient.apollo.option.OptionsImpl.postPacket(OptionsImpl.java:338)
[17:48:04] [Server thread/WARN]: 	at apollo-bukkit-1.1.1.jar//com.lunarclient.apollo.option.OptionsImpl.set(OptionsImpl.java:118)
[17:48:04] [Server thread/WARN]: 	at apollo-bukkit-1.1.1.jar//com.lunarclient.apollo.option.ConfigOptions.loadOptions(ConfigOptions.java:55)
[17:48:04] [Server thread/WARN]: 	at apollo-bukkit-1.1.1.jar//com.lunarclient.apollo.module.ApolloModuleManagerImpl.loadConfiguration(ApolloModuleManagerImpl.java:206)
[17:48:04] [Server thread/WARN]: 	at apollo-bukkit-1.1.1.jar//com.lunarclient.apollo.module.ApolloModuleManagerImpl.enableModules(ApolloModuleManagerImpl.java:83)
[17:48:04] [Server thread/WARN]: 	at apollo-bukkit-1.1.1.jar//com.lunarclient.apollo.ApolloBukkitPlatform.onEnable(ApolloBukkitPlatform.java:141)
[17:48:04] [Server thread/WARN]: 	at apollo-bukkit-1.1.1.jar//com.lunarclient.apollo.loader.BukkitPlatformLoader.onEnable(BukkitPlatformLoader.java:53)
[17:48:04] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
[17:48:04] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370)
[17:48:04] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:541)
[17:48:04] [Server thread/WARN]: 	at ServerUtils-Bukkit-3.5.4.jar//net.frankheijden.serverutils.bukkit.managers.BukkitPluginManager.enableOrderedPlugins(BukkitPluginManager.java:192)
[17:48:04] [Server thread/WARN]: 	at ServerUtils-Bukkit-3.5.4.jar//net.frankheijden.serverutils.common.managers.AbstractPluginManager.enablePlugins(AbstractPluginManager.java:105)
[17:48:04] [Server thread/WARN]: 	at ServerUtils-Bukkit-3.5.4.jar//net.frankheijden.serverutils.common.managers.AbstractPluginManager.reloadPlugins(AbstractPluginManager.java:219)
[17:48:04] [Server thread/WARN]: 	at ServerUtils-Bukkit-3.5.4.jar//net.frankheijden.serverutils.common.commands.CommandServerUtils.handleReloadPlugin(CommandServerUtils.java:243)
[17:48:04] [Server thread/WARN]: 	at ServerUtils-Bukkit-3.5.4.jar//net.frankheijden.serverutils.dependencies.cloud.execution.CommandExecutionHandler.executeFuture(CommandExecutionHandler.java:95)
[17:48:04] [Server thread/WARN]: 	at ServerUtils-Bukkit-3.5.4.jar//net.frankheijden.serverutils.dependencies.cloud.execution.CommandExecutionCoordinator$SimpleCoordinator.coordinateExecution(CommandExecutionCoordinator.java:123)
[17:48:04] [Server thread/WARN]: 	at ServerUtils-Bukkit-3.5.4.jar//net.frankheijden.serverutils.dependencies.cloud.CommandManager.executeCommand(CommandManager.java:189)
[17:48:04] [Server thread/WARN]: 	at ServerUtils-Bukkit-3.5.4.jar//net.frankheijden.serverutils.dependencies.cloud.bukkit.BukkitCommand.execute(BukkitCommand.java:116)
[17:48:04] [Server thread/WARN]: 	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159)
[17:48:04] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_18_R2.CraftServer.dispatchCommand(CraftServer.java:906)
[17:48:04] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_18_R2.CraftServer.dispatchServerCommand(CraftServer.java:869)
[17:48:04] [Server thread/WARN]: 	at net.minecraft.server.dedicated.DedicatedServer.be(DedicatedServer.java:510)
[17:48:04] [Server thread/WARN]: 	at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:484)
[17:48:04] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1456)
[17:48:04] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1226)
[17:48:04] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316)
[17:48:04] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:833)
[17:48:04] [Server thread/WARN]: java.lang.RuntimeException: Unable to wrap value of type 'Color'!
[17:48:04] [Server thread/WARN]: 	at apollo-bukkit-1.1.1.jar//com.lunarclient.apollo.option.OptionsImpl.wrapValue(OptionsImpl.java:277)
[17:48:04] [Server thread/WARN]: 	at apollo-bukkit-1.1.1.jar//com.lunarclient.apollo.option.OptionsImpl.postPacket(OptionsImpl.java:338)
[17:48:04] [Server thread/WARN]: 	at apollo-bukkit-1.1.1.jar//com.lunarclient.apollo.option.OptionsImpl.set(OptionsImpl.java:118)
[17:48:04] [Server thread/WARN]: 	at apollo-bukkit-1.1.1.jar//com.lunarclient.apollo.option.ConfigOptions.loadOptions(ConfigOptions.java:55)
[17:48:04] [Server thread/WARN]: 	at apollo-bukkit-1.1.1.jar//com.lunarclient.apollo.module.ApolloModuleManagerImpl.loadConfiguration(ApolloModuleManagerImpl.java:206)
[17:48:04] [Server thread/WARN]: 	at apollo-bukkit-1.1.1.jar//com.lunarclient.apollo.module.ApolloModuleManagerImpl.enableModules(ApolloModuleManagerImpl.java:83)
[17:48:04] [Server thread/WARN]: 	at apollo-bukkit-1.1.1.jar//com.lunarclient.apollo.ApolloBukkitPlatform.onEnable(ApolloBukkitPlatform.java:141)
[17:48:04] [Server thread/WARN]: 	at apollo-bukkit-1.1.1.jar//com.lunarclient.apollo.loader.BukkitPlatformLoader.onEnable(BukkitPlatformLoader.java:53)
[17:48:04] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
[17:48:04] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370)
[17:48:04] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:541)
[17:48:04] [Server thread/WARN]: 	at ServerUtils-Bukkit-3.5.4.jar//net.frankheijden.serverutils.bukkit.managers.BukkitPluginManager.enableOrderedPlugins(BukkitPluginManager.java:192)
[17:48:04] [Server thread/WARN]: 	at ServerUtils-Bukkit-3.5.4.jar//net.frankheijden.serverutils.common.managers.AbstractPluginManager.enablePlugins(AbstractPluginManager.java:105)
[17:48:04] [Server thread/WARN]: 	at ServerUtils-Bukkit-3.5.4.jar//net.frankheijden.serverutils.common.managers.AbstractPluginManager.reloadPlugins(AbstractPluginManager.java:219)
[17:48:04] [Server thread/WARN]: 	at ServerUtils-Bukkit-3.5.4.jar//net.frankheijden.serverutils.common.commands.CommandServerUtils.handleReloadPlugin(CommandServerUtils.java:243)
[17:48:04] [Server thread/WARN]: 	at ServerUtils-Bukkit-3.5.4.jar//net.frankheijden.serverutils.dependencies.cloud.execution.CommandExecutionHandler.executeFuture(CommandExecutionHandler.java:95)
[17:48:04] [Server thread/WARN]: 	at ServerUtils-Bukkit-3.5.4.jar//net.frankheijden.serverutils.dependencies.cloud.execution.CommandExecutionCoordinator$SimpleCoordinator.coordinateExecution(CommandExecutionCoordinator.java:123)
[17:48:04] [Server thread/WARN]: 	at ServerUtils-Bukkit-3.5.4.jar//net.frankheijden.serverutils.dependencies.cloud.CommandManager.executeCommand(CommandManager.java:189)
[17:48:04] [Server thread/WARN]: 	at ServerUtils-Bukkit-3.5.4.jar//net.frankheijden.serverutils.dependencies.cloud.bukkit.BukkitCommand.execute(BukkitCommand.java:116)
[17:48:04] [Server thread/WARN]: 	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159)
[17:48:04] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_18_R2.CraftServer.dispatchCommand(CraftServer.java:906)
[17:48:04] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_18_R2.CraftServer.dispatchServerCommand(CraftServer.java:869)
[17:48:04] [Server thread/WARN]: 	at net.minecraft.server.dedicated.DedicatedServer.be(DedicatedServer.java:510)
[17:48:04] [Server thread/WARN]: 	at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:484)
[17:48:04] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1456)
[17:48:04] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1226)
[17:48:04] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316)
[17:48:04] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:833)
[17:48:04] [Paper Async Task Handler Thread - 27/ERROR]: Caught previously unhandled exception :
[17:48:04] [Paper Async Task Handler Thread - 27/ERROR]: Paper Async Task Handler Thread - 27
java.util.ConcurrentModificationException: null
	at java.util.TreeMap$PrivateEntryIterator.nextEntry(TreeMap.java:1486) ~[?:?]
	at java.util.TreeMap$ValueIterator.next(TreeMap.java:1531) ~[?:?]
	at net.minecraft.commands.Commands.fillUsableCommands(Commands.java:414) ~[?:?]
	at net.minecraft.commands.Commands.sendAsync(Commands.java:380) ~[?:?]
	at net.minecraft.commands.Commands.sendCommands(Commands.java:364) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
[17:48:04] [Server thread/INFO]: Successfully reloaded Apollo-Bukkit!
```

**Comment by Raffymimii** [comment]
ok, nothing I fixed. I had only double-typed the mods I wanted to disable xD. Sorry for waste your time...
